name: Auto Accept PR
on:
  pull_request:
    types:
      - opened

jobs:
  auto_accept:
    runs-on: ubuntu-latest
    steps:
      - name: Check if contributor is allowed
        id: contributor_check
        run: |
          if [ "${{ github.event.pull_request.user.login }}" == "MohammadKhallaf" ]; then
            echo "::set-output name=allow::true"
          else
            echo "::set-output name=allow::false"
          fi

      - name: Auto Accept PR
        if: ${{ steps.contributor_check.outputs.allow == 'true' }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const myToken = process.env.GITHUB_TOKEN;
            const octokit = new Octokit({ auth: myToken });

            octokit.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: 'Accepted the PR! :tada:'
            });

            octokit.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              state: 'closed'
            });


            
